name: CI

on:
    push:
        branches: [main, next, workflow]
    pull_request:
        branches: [main, next]

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install yarn (required locally)
              run: npm install --global yarn
            - uses: actions/setup-node@v3
              with:
                  node-version: "22"
                  cache: "yarn"
            - name: Install dependencies
              run: yarn install --frozen-lockfile

    run-unit-tests:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Run unit tests
              run: yarn test:ci
            - uses: actions/upload-artifact@v4
              with:
                  name: test-results-unit-tests
                  path: test-result-unit.json
            - uses: dorny/test-reporter@v1.6.0
              if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
              with:
                  name: test-results / unit-tests
                  path: test-result-unit.json
                  reporter: mocha-json